-- DDLs for Budget Workflow Tables in Snowflake
-- Target Schema: APOLLO_DEVELOPMENT.FORECAST


CREATE OR REPLACE SEQUENCE FORECAST.SEQ_MANUAL_INPUT_DEPLETIONS_BUDGET_ID START = 1 INCREMENT = 1 ORDER;
CREATE OR REPLACE SEQUENCE FORECAST.SEQ_MANUAL_INPUT_DEPLETIONS_BUDGET_VERSIONS_ID START = 1 INCREMENT = 1 ORDER;

-- 1) Current-state overrides (method-agnostic) for budgets
CREATE OR REPLACE HYBRID TABLE FORECAST.MANUAL_INPUT_DEPLETIONS_BUDGET (
    ID BIGINT PRIMARY KEY DEFAULT FORECAST.SEQ_MANUAL_INPUT_DEPLETIONS_BUDGET_ID.NEXTVAL,
    MARKET_NAME VARCHAR(100),
    MARKET_CODE VARCHAR(50) NOT NULL,
    DISTRIBUTOR_NAME VARCHAR(100),
    DISTRIBUTOR_ID VARCHAR(50) NOT NULL,
    BRAND VARCHAR(100),
    BRAND_ID VARCHAR(50),
    VARIANT VARCHAR(100),
    VARIANT_ID VARCHAR(50),
    VARIANT_SIZE_PACK_DESC VARCHAR(100),
    VARIANT_SIZE_PACK_ID VARCHAR(50) NOT NULL,
    FORECAST_YEAR INTEGER NOT NULL,
    MONTH INTEGER NOT NULL,
    BUDGET_CYCLE_DATE DATE NOT NULL,
    MANUAL_CASE_EQUIVALENT_VOLUME NUMBER(28,6),
    COMMENT TEXT,
    UPDATED_BY_USER_ID VARCHAR(50),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CURRENT_VERSION INTEGER DEFAULT 1,
    INDEX idx_budget_join_keys (MARKET_CODE, DISTRIBUTOR_ID, VARIANT_SIZE_PACK_ID, FORECAST_YEAR, MONTH, BUDGET_CYCLE_DATE),
    CONSTRAINT UQ_MANUAL_BUDGET_KEY UNIQUE (market_code, distributor_id, variant_size_pack_id, forecast_year, month, budget_cycle_date)
);
COMMENT ON TABLE FORECAST.MANUAL_INPUT_DEPLETIONS_BUDGET IS 'Method-agnostic current-state manual inputs for budgets at monthly grain. Implemented as a Hybrid Table.';

-- 2) Immutable version history for budget overrides
CREATE OR REPLACE HYBRID TABLE FORECAST.MANUAL_INPUT_DEPLETIONS_BUDGET_VERSIONS (
    VERSION_ID BIGINT PRIMARY KEY DEFAULT FORECAST.SEQ_MANUAL_INPUT_DEPLETIONS_BUDGET_VERSIONS_ID.NEXTVAL,
    BUDGET_ID BIGINT NOT NULL,
    VERSION_NUMBER INTEGER NOT NULL,
    MARKET_NAME VARCHAR(100),
    MARKET_CODE VARCHAR(50) NOT NULL,
    DISTRIBUTOR_NAME VARCHAR(100),
    DISTRIBUTOR_ID VARCHAR(50) NOT NULL,
    BRAND VARCHAR(100),
    BRAND_ID VARCHAR(50),
    VARIANT VARCHAR(100),
    VARIANT_ID VARCHAR(50),
    VARIANT_SIZE_PACK_DESC VARCHAR(100),
    VARIANT_SIZE_PACK_ID VARCHAR(50) NOT NULL,
    FORECAST_YEAR INTEGER NOT NULL,
    MONTH INTEGER NOT NULL,
    BUDGET_CYCLE_DATE DATE NOT NULL,
    MANUAL_CASE_EQUIVALENT_VOLUME NUMBER(28,6),
    UPDATED_BY_USER_ID VARCHAR(50),
    COMMENT TEXT,
    VERSIONED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    INDEX idx_budget_versions_lookup (BUDGET_ID, VERSION_NUMBER),
    INDEX idx_budget_versions_join_keys (MARKET_CODE, DISTRIBUTOR_ID, VARIANT_SIZE_PACK_ID, FORECAST_YEAR, MONTH, BUDGET_CYCLE_DATE)
);
COMMENT ON TABLE FORECAST.MANUAL_INPUT_DEPLETIONS_BUDGET_VERSIONS IS 'Append-only version history of manual budget inputs. Implemented as a Hybrid Table.';

-- 3) Simplified approval/lock state per budget cycle
CREATE OR REPLACE HYBRID TABLE FORECAST.DEPLETIONS_BUDGET_APPROVALS (
    BUDGET_CYCLE_DATE DATE PRIMARY KEY,
    APPROVED_BY_USER_ID VARCHAR(50) NOT NULL,
    APPROVED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    APPROVAL_NOTE TEXT
);
COMMENT ON TABLE FORECAST.DEPLETIONS_BUDGET_APPROVALS IS 'Records approved budget cycles (FGMD) to lock further edits.';

-- 4) Runtime-generated budget output table (Y+1 only)
CREATE OR REPLACE TABLE FORECAST.DEPLETIONS_BUDGET_GENERATED (
    MARKET_NAME VARCHAR(100),
    MARKET_CODE VARCHAR(50) NOT NULL,
    DISTRIBUTOR_NAME VARCHAR(100),
    DISTRIBUTOR_ID VARCHAR(50) NOT NULL,
    BRAND VARCHAR(100),
    BRAND_ID VARCHAR(50),
    VARIANT VARCHAR(100),
    VARIANT_ID VARCHAR(50),
    VARIANT_SIZE_PACK_DESC VARCHAR(100),
    VARIANT_SIZE_PACK_ID VARCHAR(50) NOT NULL,
    FORECAST_YEAR INTEGER NOT NULL,
    MONTH INTEGER NOT NULL,
    FORECAST_MONTH_DATE DATE NOT NULL,
    FORECAST_METHOD VARCHAR(50) NOT NULL,
    CASE_EQUIVALENT_VOLUME NUMBER(28,6) NOT NULL,
    PY_CASE_EQUIVALENT_VOLUME NUMBER(28,6),
    -- Diagnostics: CY/PY rolling sums and trend factors at anchor
    CY_3M_SUM NUMBER(28,6),
    CY_6M_SUM NUMBER(28,6),
    CY_12M_SUM NUMBER(28,6),
    PY_3M_SUM NUMBER(28,6),
    PY_6M_SUM NUMBER(28,6),
    PY_12M_SUM NUMBER(28,6),
    RUN_RATE_3M NUMBER(28,6),
    TREND_FACTOR_3M NUMBER(28,6),
    TREND_FACTOR_6M NUMBER(28,6),
    TREND_FACTOR_12M NUMBER(28,6),
    DATA_SOURCE VARCHAR(50) DEFAULT 'logic_driven',
    BUDGET_CYCLE_DATE DATE NOT NULL
);
COMMENT ON TABLE FORECAST.DEPLETIONS_BUDGET_GENERATED IS 'Runtime-generated Y+1 budget records with CY/PY diagnostics and trend factors for the selected budget cycle date (FGMD). This table is rebuildable; during remap operations it may be purged/regenerated to reflect canonical IDs.';

-- 5) Budget-scoped primary forecast method
CREATE OR REPLACE HYBRID TABLE FORECAST.DEPLETIONS_BUDGET_PRIMARY_METHOD (
    BUDGET_CYCLE_DATE DATE NOT NULL,
    MARKET_CODE VARCHAR(50) NOT NULL,
    DISTRIBUTOR_ID VARCHAR(50) NOT NULL,
    VARIANT_SIZE_PACK_ID VARCHAR(50) NOT NULL,
    FORECAST_METHOD VARCHAR(50) NOT NULL,
    UPDATED_BY_USER_ID VARCHAR(50),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (BUDGET_CYCLE_DATE, MARKET_CODE, DISTRIBUTOR_ID, VARIANT_SIZE_PACK_ID)
);
COMMENT ON TABLE FORECAST.DEPLETIONS_BUDGET_PRIMARY_METHOD IS 'Budget-scoped primary forecast method per key.';

