# Dagster OSS instance configuration (Render/Prod)
# Copy to $DAGSTER_HOME/dagster.yaml at container start.

storage:
  postgres:
    postgres_db:
      hostname:
        env: DAGSTER_PG_HOST
      port:
        env: DAGSTER_PG_PORT
      db_name:
        env: DAGSTER_PG_DB
      username:
        env: DAGSTER_PG_USER
      password:
        env: DAGSTER_PG_PASSWORD

run_queue:
  max_concurrent_runs: 10

scheduler:
  module: dagster.core.scheduler
  class: DagsterDaemonScheduler

telemetry:
  enabled: false
