-- Chains Publishing Workflow - Test Cleanup
-- Cleans up all test data created during the test suite

USE DATABASE APOLLO_DEVELOPMENT;

SELECT '🧹 CLEANING UP TEST DATA' AS OPERATION;

-- =========================================
-- CLEANUP PUBLISHED FORECASTS
-- =========================================

-- Clean up chains published forecasts
DELETE FROM FORECAST.DEPLETIONS_FORECAST_PUBLISHED_FORECASTS_CHAINS 
WHERE MARKET_CODE IN ('USANY1', 'USAPA1');

SELECT 'Cleaned up chains published forecasts' AS STEP, ROW_COUNT() AS ROWS_DELETED;

-- Clean up core published forecasts
DELETE FROM FORECAST.DEPLETIONS_FORECAST_PUBLISHED_FORECASTS 
WHERE MARKET_CODE IN ('USANY1', 'USAPA1');

SELECT 'Cleaned up core published forecasts' AS STEP, ROW_COUNT() AS ROWS_DELETED;

-- =========================================
-- CLEANUP PUBLICATION METADATA
-- =========================================

-- Clean up publications
DELETE FROM FORECAST.DEPLETIONS_FORECAST_PUBLICATIONS 
WHERE MARKET_CODE IN ('USANY1', 'USAPA1');

SELECT 'Cleaned up publications' AS STEP, ROW_COUNT() AS ROWS_DELETED;

-- Clean up publication groups
DELETE FROM FORECAST.DEPLETIONS_FORECAST_PUBLICATION_GROUPS 
WHERE DIVISION IN ('Independent Franchise', 'BBG and Control');

SELECT 'Cleaned up publication groups' AS STEP, ROW_COUNT() AS ROWS_DELETED;

-- =========================================
-- CLEANUP CHAINS MANUAL DATA
-- =========================================

-- Clean up chains manual forecast versions
DELETE FROM FORECAST.MANUAL_INPUT_DEPLETIONS_FORECAST_CHAINS_VERSIONS 
WHERE FORECAST_ID IN (
    SELECT ID FROM FORECAST.MANUAL_INPUT_DEPLETIONS_FORECAST_CHAINS 
    WHERE MARKET_CODE IN ('USANY1', 'USAPA1')
);

SELECT 'Cleaned up chains manual forecast versions' AS STEP, ROW_COUNT() AS ROWS_DELETED;

-- Clean up chains manual forecasts
DELETE FROM FORECAST.MANUAL_INPUT_DEPLETIONS_FORECAST_CHAINS 
WHERE MARKET_CODE IN ('USANY1', 'USAPA1');

SELECT 'Cleaned up chains manual forecasts' AS STEP, ROW_COUNT() AS ROWS_DELETED;

-- =========================================
-- CLEANUP CHAINS DRAFT DATA
-- =========================================

-- Clean up chains draft forecasts
DELETE FROM FORECAST.DEPLETIONS_FORECAST_INIT_DRAFT_CHAINS 
WHERE MARKET_CODE IN ('USANY1', 'USAPA1');

SELECT 'Cleaned up chains draft forecasts' AS STEP, ROW_COUNT() AS ROWS_DELETED;

-- Clean up chains primary forecast methods
DELETE FROM FORECAST.DEPLETIONS_FORECAST_PRIMARY_FORECAST_METHOD_CHAINS 
WHERE MARKET_CODE IN ('USANY1', 'USAPA1');

SELECT 'Cleaned up chains primary forecast methods' AS STEP, ROW_COUNT() AS ROWS_DELETED;

-- =========================================
-- CLEANUP CORE VOLUME DATA
-- =========================================

-- Clean up core draft forecasts
DELETE FROM FORECAST.DEPLETIONS_FORECAST_INIT_DRAFT 
WHERE MARKET_CODE IN ('USANY1', 'USAPA1');

SELECT 'Cleaned up core draft forecasts' AS STEP, ROW_COUNT() AS ROWS_DELETED;

-- Clean up core manual forecasts
DELETE FROM FORECAST.MANUAL_INPUT_DEPLETIONS_FORECAST 
WHERE MARKET_CODE IN ('USANY1', 'USAPA1');

SELECT 'Cleaned up core manual forecasts' AS STEP, ROW_COUNT() AS ROWS_DELETED;

-- Clean up core primary forecast methods
DELETE FROM FORECAST.DEPLETIONS_FORECAST_PRIMARY_FORECAST_METHOD 
WHERE MARKET_CODE IN ('USANY1', 'USAPA1');

SELECT 'Cleaned up core primary forecast methods' AS STEP, ROW_COUNT() AS ROWS_DELETED;

-- =========================================
-- CLEANUP MASTER DATA
-- =========================================

-- Note: Not cleaning up division hierarchy since we're using real data
SELECT 'Skipped division hierarchy cleanup (using real data)' AS STEP, 0 AS ROWS_DELETED;

-- =========================================
-- VERIFICATION
-- =========================================

SELECT '📊 CLEANUP VERIFICATION' AS SECTION;

-- Verify all test data is cleaned up
SELECT 
    'CHAINS_PUBLISHED_FORECASTS' AS TABLE_NAME, COUNT(*) AS REMAINING_RECORDS
FROM FORECAST.DEPLETIONS_FORECAST_PUBLISHED_FORECASTS_CHAINS 
WHERE MARKET_CODE IN ('USANY1', 'USAPA1')

UNION ALL

SELECT 
    'CORE_PUBLISHED_FORECASTS' AS TABLE_NAME, COUNT(*) AS REMAINING_RECORDS
FROM FORECAST.DEPLETIONS_FORECAST_PUBLISHED_FORECASTS 
WHERE MARKET_CODE IN ('USANY1', 'USAPA1')

UNION ALL

SELECT 
    'PUBLICATIONS' AS TABLE_NAME, COUNT(*) AS REMAINING_RECORDS
FROM FORECAST.DEPLETIONS_FORECAST_PUBLICATIONS 
WHERE MARKET_CODE IN ('USANY1', 'USAPA1')

UNION ALL

SELECT 
    'PUBLICATION_GROUPS' AS TABLE_NAME, COUNT(*) AS REMAINING_RECORDS
FROM FORECAST.DEPLETIONS_FORECAST_PUBLICATION_GROUPS 
WHERE DIVISION IN ('Independent Franchise', 'BBG and Control')

UNION ALL

SELECT 
    'CHAINS_MANUAL_FORECASTS' AS TABLE_NAME, COUNT(*) AS REMAINING_RECORDS
FROM FORECAST.MANUAL_INPUT_DEPLETIONS_FORECAST_CHAINS 
WHERE MARKET_CODE IN ('USANY1', 'USAPA1')

UNION ALL

SELECT 
    'CHAINS_DRAFT_FORECASTS' AS TABLE_NAME, COUNT(*) AS REMAINING_RECORDS
FROM FORECAST.DEPLETIONS_FORECAST_INIT_DRAFT_CHAINS 
WHERE MARKET_CODE IN ('USANY1', 'USAPA1')

UNION ALL

SELECT 
    'CHAINS_PRIMARY_METHODS' AS TABLE_NAME, COUNT(*) AS REMAINING_RECORDS
FROM FORECAST.DEPLETIONS_FORECAST_PRIMARY_FORECAST_METHOD_CHAINS 
WHERE MARKET_CODE IN ('USANY1', 'USAPA1')

UNION ALL

SELECT 
    'CORE_DRAFT_FORECASTS' AS TABLE_NAME, COUNT(*) AS REMAINING_RECORDS
FROM FORECAST.DEPLETIONS_FORECAST_INIT_DRAFT 
WHERE MARKET_CODE IN ('USANY1', 'USAPA1')

UNION ALL

SELECT 
    'CORE_MANUAL_FORECASTS' AS TABLE_NAME, COUNT(*) AS REMAINING_RECORDS
FROM FORECAST.MANUAL_INPUT_DEPLETIONS_FORECAST 
WHERE MARKET_CODE IN ('USANY1', 'USAPA1')

UNION ALL

SELECT 
    'DIVISION_HIERARCHY' AS TABLE_NAME, 'SKIPPED (REAL DATA)' AS REMAINING_RECORDS
FROM (SELECT 1) dummy;

COMMIT;

-- Final status
SELECT 
    CASE 
        WHEN (
            SELECT SUM(remaining_count) FROM (
                SELECT COUNT(*) AS remaining_count FROM FORECAST.DEPLETIONS_FORECAST_PUBLISHED_FORECASTS_CHAINS WHERE MARKET_CODE IN ('USANY1', 'USAPA1')
                UNION ALL SELECT COUNT(*) FROM FORECAST.DEPLETIONS_FORECAST_PUBLISHED_FORECASTS WHERE MARKET_CODE IN ('USANY1', 'USAPA1')
                UNION ALL SELECT COUNT(*) FROM FORECAST.DEPLETIONS_FORECAST_PUBLICATIONS WHERE MARKET_CODE IN ('USANY1', 'USAPA1')
                UNION ALL SELECT COUNT(*) FROM FORECAST.DEPLETIONS_FORECAST_PUBLICATION_GROUPS WHERE DIVISION IN ('Independent Franchise', 'BBG and Control')
                UNION ALL SELECT COUNT(*) FROM FORECAST.MANUAL_INPUT_DEPLETIONS_FORECAST_CHAINS WHERE MARKET_CODE IN ('USANY1', 'USAPA1')
                UNION ALL SELECT COUNT(*) FROM FORECAST.DEPLETIONS_FORECAST_INIT_DRAFT_CHAINS WHERE MARKET_CODE IN ('USANY1', 'USAPA1')
                UNION ALL SELECT COUNT(*) FROM FORECAST.DEPLETIONS_FORECAST_PRIMARY_FORECAST_METHOD_CHAINS WHERE MARKET_CODE IN ('USANY1', 'USAPA1')
            )
        ) = 0 
        THEN '✅ CLEANUP COMPLETE - ALL TEST DATA REMOVED'
        ELSE '❌ CLEANUP INCOMPLETE - SOME TEST DATA REMAINS'
    END AS CLEANUP_STATUS;