
CREATE OR REPLACE TABLE MASTER_DATA.CUSTOM_PRODUCT_AUDIT (
  EVENT_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
  EVENT_TYPE VARCHAR, -- create, update, toggle_planned, update_exclusions, seed_zero, remap, dry_run
  VARIANT_SIZE_PACK_ID VARCHAR,
  PAYLOAD VARIANT,
  ROW_COUNT INTEGER,
  CORRELATION_ID VARCHAR,
  ACTOR VARCHAR,
  EVENT_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COMMENT ON TABLE MASTER_DATA.CUSTOM_PRODUCT_AUDIT IS 'Audit log for custom product operations, zero seeding, and remapping.';
